### PR TITLE
Remove poetry.lock file for this library package

### PR DESCRIPTION
**Pull request by Purg**
General advice is that of library packages do not need to stick to
static locked depedencies.

* Add lock file to ignore
* CI uses hash around pyproject.toml instead of lock file.
* Fix some docs related to poetry use

### CODE REVIEW

**Comment by Purg** [comment]
For requested reviewers: I'm mostly asking for a sanity check on your understanding or perception of lock files for libraries. Currently I've read that "libraries" (vs. "applications") generally do not need to have lock files established, just the abstract requirements and the versioning needed therein (e.g. major version window). This package, as well as the other smqtk-* packages thus far, have a bare minimum of required packages if any at all (like none for this core), so pinning versions would be for development deps for testing, docs building and CI. I could imagine arguments both for and against, but I'm all for the side of not pinning (less complexity) until we find that we need to.

**Comment by bardkw** [comment]
Can confirm. On the official docs, it was mentioned that it was optional for libraries to commit the lockfiles. I'm not exactly sure why its considered optional there, but if you think it would make it less complex then I think its fine to go ahead with it

**Comment by waxlamp** [comment]
Locking packages generally is an advantage for developers, so that things don't change under them unexpectedly. Pinned package versions for distributed libraries is indeed a bad idea, since your library will quickly go out of date with the latest versions of dependencies, and eventually become impossible to install for end users.

I'm not sure what the connection is between poetry's locked dependencies, and its publishing algorithm. If poetry generates packages with loose install-time dependency versions, even with a lockfile, then my default position would be to keep the lockfile and do fairly regular package _upgrades_ in order to keep up with latest installed dependencies. This gives you more developer stability at the cost of an extra administrative step that has to be on some sort of schedule.

The other option is to do what you've opted for, which has the advantage of not needing to worry about dependency upgrades, but could possibly cause some issues for different people working on the codebase. I think your approach will be fine, especially now that we're early in this venture.

**Comment by Purg** [comment]
> I'm not sure what the connection is between poetry's locked dependencies, and its publishing algorithm.

There is no connection between the lock file and poetry package building. The lock file is just for a local `poetry install` which installs both required and dev depedencies at the lockfile-specified versions if the file is present (other wise it makes one based on the latest version available at the time of the install that fit the abstract requirements). The packages built via `poetry build` encode the abstract version requirements defined in the `pyproject.toml`.

**Comment by Purg** [comment]
I'm on the edge myself, but I'm getting a sense of keeping the lock file from the both of you, so lets do that for now. I will try out a scheduled `poetry update` session for the family of repos here and see how that goes.

**Pull request closed without merging**
